"""
You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.

Write a function that returns the letter that was added to str_2.

Examples:

csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"
Notes:

str_1 and str_2 both consist of only lowercase alpha characters.

"""


def find_added_letter(s1, s2):
    s1, s2 = sorted(s1), sorted(s2)

    for c1, c2 in zip(s1, s2):
        if c1 != c2:
            return c2

    return s2[-1]


if __name__ == '__main__':
    res1 = find_added_letter("bcde", "bcdef")  # -> "f"
    print(res1)
